export default {
  SELECTED_THEME: '@WEATHERING_C/SELECTED_THEME',
  SLICE_USER: '@WEATHERING_C/SLICE/USER',
  SLICE_LOCATION: '@WEATHERING_C/SLICE/LOCATION',
  SLICE_CLIMATE: '@WEATHERING_C/SLICE/CLIMATE',
};
